name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: |
        sudo apt install gcc-aarch64-linux-gnu iasl device-tree-compiler python3-pyelftools
    - name: Build
      run: |
        make sdcard
    
